services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      # https://spring.io/guides/gs/spring-boot-docker
      - SPRING_PROFILES_ACTIVE=dev
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    command: ./gradlew bootRun
    tty: true
    stdin_open: true
